### ISSUE TITLE
Possible Refactoring in `schema::types` module

### ISSUE THREAD

**Issue by rajarshimaitra** [LNP-BP/rust-lnpbp#111]
There seems to be an awkward import here with `pub use elliptic_curve::EllipticCurve;` 
https://github.com/LNP-BP/rust-lnpbp/blob/5092e26e5fee72e7c8201c8f29064bcb412ee6e7/src/rgb/schema/types.rs#L251-L259

Was this intentional? Why specifically import `EllipticCurve` like this and not do the same for `SignatureAlgorithm` and `PointSerialization`?

**Comment by dr-orlovsky** [comment]
This is intentional. I needed a namespace for all EC-related types just not to mix with the rest. However, main type, which name is equivalent to the mod name, should be imported directly, just not to write `elliptic_curve::EllipticCurve` tautology and use just `EllipticCurve` instead (while it must be `elliptic_curve::SignatureAlgorithm`)
